# -*- coding: utf-8 -*-
"""UNLOX2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pc0MVtJCEKfQOpfTN9p9i_OdfKD_5TUl
"""

# Dictionary storing ATM account details
# Each account number has a PIN and a balance
accounts = {
    "1001": {"pin": "1234", "balance": 5000},
    "1002": {"pin": "4321", "balance": 8000},
    "1003": {"pin": "1111", "balance": 10000}
}

# Display welcome message
print("Welcome to ATM")

# Ask the user to enter account number
acc_no = input("Enter Account Number: ")

# Ask the user to enter PIN
pin = input("Enter PIN: ")

# Check if the account number exists and the PIN is correct
if acc_no in accounts and accounts[acc_no]["pin"] == pin:

    print("Login Successful")

    # Loop to allow multiple transactions until user exits
    while True:

        # Display ATM menu options
        print("\n1. Withdraw")
        print("2. Deposit")
        print("3. Check Balance")
        print("4. Exit")

        # Take user's choice
        choice = int(input("Enter your choice: "))

        # Withdraw option
        if choice == 1:
            amount = int(input("Enter amount to withdraw: "))

            # Check if sufficient balance is available
            if amount <= accounts[acc_no]["balance"]:

                # Deduct the amount from the balance
                accounts[acc_no]["balance"] -= amount

                print("Transaction Successful")
                print("Remaining Balance:", accounts[acc_no]["balance"])
            else:
                print("Insufficient Balance")

        # Deposit option
        elif choice == 2:

            # Ask the user how much money to deposit
            amount = int(input("Enter amount to deposit: "))

            # Add the amount to the account balance
            accounts[acc_no]["balance"] += amount

            print("Deposit Successful")
            print("Updated Balance:", accounts[acc_no]["balance"])

        # Check balance option
        elif choice == 3:

            # Display current account balance
            print("Your Balance:", accounts[acc_no]["balance"])

        # Exit option
        elif choice == 4:

            # Break will stop the loop and exit the ATM system
            print("Thank you for using ATM")
            break

        # If user enters an invalid option
        else:
            print("Invalid choice")

# If account number or PIN is wrong
else:
    print("Invalid Account Number or PIN")